// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	storage "github.com/hromov/storage/domain/storage"
)

// MockFileService is a mock of FileService interface.
type MockFileService struct {
	ctrl     *gomock.Controller
	recorder *MockFileServiceMockRecorder
}

// MockFileServiceMockRecorder is the mock recorder for MockFileService.
type MockFileServiceMockRecorder struct {
	mock *MockFileService
}

// NewMockFileService creates a new mock instance.
func NewMockFileService(ctrl *gomock.Controller) *MockFileService {
	mock := &MockFileService{ctrl: ctrl}
	mock.recorder = &MockFileServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileService) EXPECT() *MockFileServiceMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockFileService) Save(c storage.FileCategory, fileName string, file io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", c, fileName, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockFileServiceMockRecorder) Save(c, fileName, file interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockFileService)(nil).Save), c, fileName, file)
}

// MockNotifierService is a mock of NotifierService interface.
type MockNotifierService struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierServiceMockRecorder
}

// MockNotifierServiceMockRecorder is the mock recorder for MockNotifierService.
type MockNotifierServiceMockRecorder struct {
	mock *MockNotifierService
}

// NewMockNotifierService creates a new mock instance.
func NewMockNotifierService(ctrl *gomock.Controller) *MockNotifierService {
	mock := &MockNotifierService{ctrl: ctrl}
	mock.recorder = &MockNotifierServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifierService) EXPECT() *MockNotifierServiceMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockNotifierService) Notify(arg0 storage.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Notify indicates an expected call of Notify.
func (mr *MockNotifierServiceMockRecorder) Notify(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockNotifierService)(nil).Notify), arg0)
}
