name: Go

on:
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

#       - name: Build
#         run: make build-server

      - name: Lint
        uses: golangci/golangci-lint-action@v3.2.0

#       - name: Test
#         run: make test
